"""Generate fixed CPython/QRT2 fixtures consumed by Kotlin JVM tests."""

from __future__ import annotations

import base64
import random
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from common.lt_wrapper import LTEncoder, _block_indices
from common.qr_wire import pack_packet


def b64(value: bytes) -> str:
    return base64.b64encode(value).decode("ascii")


def main() -> None:
    lines = ["# Generated by protocol/tools/generate_golden_vectors.py using CPython " + sys.version.split()[0]]
    for seed in (0, 1, 0x51515151, 0xFFFFFFFF):
        rng = random.Random(seed)
        lines.append(f"bits8.{seed}=" + ",".join(str(rng.getrandbits(8)) for _ in range(16)))
        rng = random.Random(seed)
        bits = [8, 32, 53, 63]
        lines.append(f"mixedbits.{seed}=" + ",".join(str(rng.getrandbits(k)) for k in bits))
        rng = random.Random(seed)
        lines.append(
            f"randomBits.{seed}="
            + ",".join(f"{struct.unpack('>Q', struct.pack('>d', rng.random()))[0]:016x}" for _ in range(8))
        )
    for seed, n, count in ((0, 10, 4), (7, 100, 3), (99, 50, 10), (0xFFFFFFFF, 1000, 30)):
        result = random.Random(seed).sample(range(n), count)
        lines.append(f"sample.{seed}.{n}.{count}=" + ",".join(map(str, result)))
    for total_k, seq, seed in ((10, 10, 10), (50, 53, 53), (300, 450, 450)):
        lines.append(
            f"indices.{total_k}.{seq}.{seed}="
            + ",".join(map(str, sorted(_block_indices(total_k, seq, seed))))
        )

    original = bytes((index * 37 + 11) % 256 for index in range(301))
    encoder = LTEncoder(original, chunk_size=32, seed=0)
    lines += [
        f"lt.original={b64(original)}",
        f"lt.totalK={encoder.total_k}",
        f"lt.count={encoder.total_k * 3}",
    ]
    filename = "검증-data.bin"
    for seq in range(encoder.total_k * 3):
        packet = encoder.packet(seq)
        fields = [
            str(packet["seq"]),
            str(packet["seed"]),
            str(packet["total_k"]),
            str(packet["file_hash"]),
            b64(filename.encode("utf-8")),
            b64(packet["data"]),
            pack_packet(packet, filename).decode("ascii"),
        ]
        lines.append(f"lt.packet.{seq}=" + "|".join(fields))

    destination = ROOT / "android-validator/protocol/src/test/resources/golden_vectors.properties"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(destination)


if __name__ == "__main__":
    main()

